apiVersion: v1
kind: Service
metadata:
    annotations:
        service.beta.kubernetes.io/azure-dns-label-name: remstrava
    name: remsterremstravafrontend
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: remsterremstravafrontend
